## It seems like the yml file can control certain things (directories, toc, etc.) but doesn't work for other things (chunk_output_type). In summary, the _yml file is important still. 

project:
  type: default
  execute-dir: project
  output-dir: Derived/PDF/
format: 
  pdf:
    pdf-engine: lualatex
    toc: true
    toc-depth: 3 
    author-affiliations: true
    template-partials:
      - Quarto_supp_files/title.tex
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
    #lof: true
    #lot: true
editor:
  root-dir: "/Users/aaronskinner/Library/CloudStorage/OneDrive-UBC/Grad_School/PhD/Analysis/Colombia-SCR-Rd3"
editor_options: 
  chunk_output_type: console
  date: today
  date-format: long
date: today
date-format: long